config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'quns#index'

resources :quns do
  resources :posts
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :qun
end

app/models/qun.rb
class Qun < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :quns
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @qun = Qun.find(params[:qun_id])
    @post = Post.new
  end

  def create
    @qun = Qun.find(params[:qun_id])
    @post = Post.new(post_params)
    @post.qun = @qun
    @post.user = current_user

    if @post.save
      redirect_to qun_path(@qun)
    else
      render :new
    end
  end


  private

  def post_params
    params.require(:post).permit(:content)
  end

end

app/controllers/quns_controller.rb
class QunsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_qun_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @quns = Qun.all
  end

  def show
    @qun = Qun.find(params[:id])
  end

  def new
    @qun = Qun.new
  end

  def create
    @qun = Qun.new(qun_params)
    @qun.user = current_user
    if @qun.save
      redirect_to quns_path
    else
      render :new
    end
  end

  def edit
  end

   def update
     if @qun.update(qun_params)
       redirect_to quns_path, notice: "Update Success"
     else
       render :edit
     end
   end

  def destroy
    @qun.destroy
    redirect_to quns_path, alert: "Qun deleted"
  end

  private
  def find_qun_and_check_permission
    @qun = Qun.find(params[:id])

    if current_user != @qun.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def qun_params
    params.require(:qun).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quns_helper.rb
module QunsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>

            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Rails101</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/posts/new.html.erb
<h2 class="text-center">新增文章</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@qun,@post] do |f| %>
    <div class="form-qun">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/quns/_form.html.erb
<%= simple_form_for @qun do |f| %>
  <div class="form-qun">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/quns/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑讨论版</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/quns/index.html.erb
<div class="col-md-12">
  <div class="qun">
    <%= link_to("New qun", new_qun_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>Creator </td>
      </tr>
    </thead>
    <tbody>
      <% @quns.each do |qun| %>
        <tr>
          <td>#</td>
          <td><%= link_to(qun.title, qun_path(qun)) %></td>
          <td><%= qun.description %></td>
          <td> <%= qun.user.email %> </td>
          <td>
              <% if current_user && current_user == qun.user %>
                 <%= link_to("Edit", edit_qun_path(qun), class: "btn btn-sm btn-default")%>
                 <%= link_to("Delete", qun_path(qun),    class: "btn btn-sm btn-default",
                             method: :delete, data: { confirm: "Are you sure?" } )%>
              <% end %>
              </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/quns/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增讨论版</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/quns/show.html.erb
<div class="col-md-12">
  <div class="qun">
    <%= link_to("Write a Post", new_qun_post_path(@qun), class: "btn btn-default pull-right")%>
    <% if current_user && current_user == @qun.user %>
      <%= link_to("Edit", edit_qun_path(@qun), class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
  <h2><%= @qun.title %></h2>
  <p><%= @qun.description %></p>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>